ALTER TABLE aplicacion ADD COLUMN IF NOT EXISTS ec2_host TEXT;
ALTER TABLE aplicacion ADD COLUMN IF NOT EXISTS ec2_user TEXT;
ALTER TABLE aplicacion ADD COLUMN IF NOT EXISTS ec2_llave_ssh TEXT;
ALTER TABLE aplicacion ADD COLUMN IF NOT EXISTS ec2_known_hosts TEXT;
ALTER TABLE aplicacion ADD COLUMN IF NOT EXISTS app_port INTEGER;
