version: "3"  # Versión del archivo Docker Compose

services:
  sonarqube:
    image: sonarqube:community  # Imagen oficial de la edición Community de SonarQube
    ports:
      - "9000:9000"  # Expongo el puerto 9000 del contenedor al host
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true  # Desactivo chequeos de memoria que a veces fallan en entornos locales
    volumes:
      - sonarqube_data:/opt/sonarqube/data         # Persistencia de datos de SonarQube
      - sonarqube_extensions:/opt/sonarqube/extensions  # Persistencia de extensiones o plugins
      - sonarqube_logs:/opt/sonarqube/logs         # Persistencia de logs para diagnósticos

# Defino volúmenes para que la información no se pierda al reiniciar o eliminar el contenedor
volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs: