name: CI-__APP_NAME__

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build & Test (Maven)
        run: |
          if [ -f "./mvnw" ]; then
            chmod +x ./mvnw
            ./mvnw -B -f pom.xml test
          else
            mvn -B -f pom.xml test
          fi

  sonar:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: SonarCloud Analysis (optional)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
        run: |
          if [ -z "$SONAR_TOKEN" ] || [ -z "$SONAR_PROJECT_KEY" ] || [ -z "$SONAR_ORGANIZATION" ]; then
            echo "Sonar secrets not configured. Skipping Sonar analysis."
            exit 0
          fi

          if [ -f "./mvnw" ]; then
            chmod +x ./mvnw
            ./mvnw -B -f pom.xml verify sonar:sonar \
              -Dsonar.projectKey="${SONAR_PROJECT_KEY}" \
              -Dsonar.organization="${SONAR_ORGANIZATION}" \
              -Dsonar.host.url="${SONAR_HOST_URL}"
          else
            mvn -B -f pom.xml verify sonar:sonar \
              -Dsonar.projectKey="${SONAR_PROJECT_KEY}" \
              -Dsonar.organization="${SONAR_ORGANIZATION}" \
              -Dsonar.host.url="${SONAR_HOST_URL}"
          fi

  build_and_push_ecr:
    runs-on: ubuntu-latest
    needs: build_and_test
    # Push a main y tags (NO PR)
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker image
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          set -e
          ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
          IMAGE_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"

          echo "Building image: ${IMAGE_URI}"
          docker build -t "${IMAGE_URI}" .

          echo "Tagging latest..."
          docker tag "${IMAGE_URI}" "${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"

          echo "Pushing images..."
          docker push "${IMAGE_URI}"
          docker push "${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"

          echo "Done ✅"

  deploy_ec2:
    runs-on: ubuntu-latest
    needs: build_and_push_ecr
    if: startsWith(github.ref, 'refs/tags/')

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_LLAVE_SSH: ${{ secrets.EC2_LLAVE_SSH }}
      EC2_KNOWN_HOSTS: ${{ secrets.EC2_KNOWN_HOSTS }}

      IMAGE_TAG: ${{ github.sha }}

      # DB secrets (válido para mongo/mysql/postgres)
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      # App
      APP_PORT: ${{ secrets.APP_PORT }}

    steps:
      - uses: actions/checkout@v4

      - name: Preparar clave SSH
        run: |
          set -e
          mkdir -p ~/.ssh
          printf "%s" "${EC2_LLAVE_SSH}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          if [ -n "${EC2_KNOWN_HOSTS}" ]; then
            echo "${EC2_KNOWN_HOSTS}" > ~/.ssh/known_hosts
          else
            ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
          fi

      - name: Subir docker-compose.yml a EC2
        run: |
          set -e
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes "$EC2_USER@$EC2_HOST" "mkdir -p ~/app"
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes docker-compose.yml "$EC2_USER@$EC2_HOST:~/app/docker-compose.yml"

      - name: Ejecutar despliegue en EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes "$EC2_USER@$EC2_HOST" "
            set -e

            # AWS CLI (para login ECR)
            if ! command -v aws >/dev/null 2>&1; then
              sudo apt-get update -y
              sudo apt-get install -y awscli
            fi

            # Docker
            if ! command -v docker >/dev/null 2>&1; then
              sudo apt-get update -y
              sudo apt-get install -y docker.io
              sudo systemctl enable --now docker
            fi

            # Docker Compose plugin (sin apt): instalar binario si no existe
            if ! sudo docker compose version >/dev/null 2>&1; then
              sudo mkdir -p /usr/local/lib/docker/cli-plugins
              sudo curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
                -o /usr/local/lib/docker/cli-plugins/docker-compose
              sudo chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
            fi

            # Variables (con defaults)
            export AWS_ACCESS_KEY_ID='${AWS_ACCESS_KEY_ID}'
            export AWS_SECRET_ACCESS_KEY='${AWS_SECRET_ACCESS_KEY}'
            export AWS_REGION='${AWS_REGION}'

            export DB_ENGINE='${DB_ENGINE}'
            export DB_HOST='${DB_HOST}'
            export DB_PORT='${DB_PORT}'
            export DB_NAME='${DB_NAME}'
            export DB_USER='${DB_USER}'
            export DB_PASSWORD='${DB_PASSWORD}'

            if [ -n '${APP_PORT}' ]; then
              export APP_PORT='${APP_PORT}'
            else
              export APP_PORT='8081'
            fi

            ECR_REGISTRY='${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com'
            export IMAGE_URI=\"\${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}\"

            echo \"Login ECR: \${ECR_REGISTRY}\"
            aws ecr get-login-password --region \"${AWS_REGION}\" \
              | sudo -E docker login --username AWS --password-stdin \"\${ECR_REGISTRY}\"

            cd ~/app

            # Genérico: apaga el stack anterior (sirve para cualquier nombre de contenedor/motor)
            sudo -E docker compose -f docker-compose.yml down --remove-orphans || true

            # IMPORTANTE: -E para que docker compose vea IMAGE_URI/DB_*/APP_PORT
            sudo -E docker compose -f docker-compose.yml pull
            sudo -E docker compose -f docker-compose.yml up -d --remove-orphans
            sudo docker image prune -f
          "